### ISSUE TITLE
TubumuMeeting.Meeting.Client.WPF 连接失败

### ISSUE THREAD

**Issue by fcgll520** [albyho/TubumuMeeting#2]
![image](https://user-images.githubusercontent.com/8245015/84382037-99f12180-ac1c-11ea-85fd-a04bbd6d0615.png)
![image](https://user-images.githubusercontent.com/8245015/84382156-d58beb80-ac1c-11ea-939f-e56d884e4fa7.png)

请问下，这个错误是什么原因？
web客户端是正常的。

**Comment by albyho** [comment]
WPF客户端还没完善。SignalR 是接通了的，相关接口已经不一致了。

**Comment by fcgll520** [comment]
好的，找到了个规避方法
