### ISSUE TITLE
@release mode log shows 0 consumers and it closes

### ISSUE THREAD

**Issue by bakamaru** [albyho/TubumuMeeting#21]
I've tried your demo and its good though I've face little problems here.
1.It's showing same local stream and remote streams for same device causing noisy echo.so how to stop receiving own produced stream  as consumer.
2.on debug mode looks like fine but in release mode.streams are closed within a few seconds. as log shows 0 consumers and it closes worker.is it signalr problem?(ps on release mode 10 sec has given to check consumer and then connection/producer/consumer lost)

![image](https://user-images.githubusercontent.com/1064348/125245548-69dcec00-e310-11eb-90cb-db386fac5724.png)

**Comment by albyho** [comment]
1. Don't show  local stream or don't create consumers for own producers.
https://github.com/albyho/Tubumu.Meeting.Demo/blob/f45e8d4958cbfff1b5680a4cc5ef4b0d271d5586/tubumu-meeting-demo-client/src/App.vue#L952
https://github.com/albyho/Tubumu.Meeting.Demo/blob/f45e8d4958cbfff1b5680a4cc5ef4b0d271d5586/tubumu-meeting-demo-client/src/App.vue#L468
2. Yes, the producer will be closed after 10 seconds if there are no consumers. You can change it.
https://github.com/albyho/Tubumu.Mediasoup/blob/4389e5e2046f1c8c23ad3c440e5cdec20027de95/Producer/Producer.cs#L65

**Comment by bakamaru** [comment]
Thank you for your quick response and another question,how far it can be scaled? or how many participant can join in single room(ps i've 10 core server 32gig ram.)

**Comment by albyho** [comment]
See: https://mediasoup.discourse.group/t/experience-with-mediasoup/1578
