### ISSUE TITLE
How do i scale up

### ISSUE THREAD

**Issue by bakamaru** [albyho/TubumuMeeting#25]
With this project,how many user can join in conference room? and how many users for webinar (single video/audio producer) in single windows server?

**Comment by albyho** [comment]
See: [https://mediasoup.discourse.group/t/experience-with-mediasoup/1578](https://mediasoup.discourse.group/t/experience-with-mediasoup/1578)

**Comment by bakamaru** [comment]
Does it applies to your demo app as well?I find lagging during testing how can i manage that issue? or is it because of windows server ?

**Comment by bakamaru** [comment]
Is there way to distribute load across all available worker of all room or single room?right now single room assigned to  single worker when user increases single worker routing are delaying.

**Comment by albyho** [comment]
1. One room - One worker(router).
2. One room - Multiple workers(routers). Use `pipeToRouter`, this is an example: [https://github.com/edumeet/edumeet](https://github.com/edumeet/edumeet)
